### ISSUE TITLE
Openess & No Monopoly/GenerateAnd Sign: The choice of MORoot must be an input parameter

### ISSUE THREAD

**Issue by JMR-Gireve** [charinev/opnc#11]
Openess & No Monopoly/GenerateAnd Sign: The choice of MORoot must be an input parameter

A PKI-services-provider could offer to generate contract certificates with various MORoot-CAs. eMSP must be able to select which MO-RootCA will be used. 

Benefits: Market openess. Usefull at least for CharINV2GRootCA

Impact son players already connected via OPCP:none (new optional input parameter)"

**Comment by MKeCharIN** [comment]
@JMR-Gireve , additional parameter to be added via pull request.
