### ISSUE TITLE
Key topic for maintenance/Add an explicit identification of each exchanged messages: Add an explicit identification of exchanges messages to improve maintenance and diagnosis 

### ISSUE THREAD

**Issue by JMR-Gireve** [charinev/opnc#12]
Key topic for maintenance/Add an explicit identification of each exchanged messages: Add an explicit identification of exchanges messages to improve maintenance and diagnosis 

Proposition to add http headers : “OPNC-Request-Id”, and “OPNC-Correlation-Id”

Benefits:
1°)in case of incident or malfunction diagnosis both parties can easilly identify which message (which API request/response) they have to analyse. They are sure to talk about the same message.
2°)Compliancy with OCPI and thus with the majority of eMSP and CPO

Impacts on players already connected via OPCP: no negative impact (because optional to read them). Positive impact: operation, maintenance and security improvement"

**Comment by MKeCharIN** [comment]
This is a new general request for a functional change, which can be discussed in the group meeting.

**Comment by steffenrhinow** [comment]
I'm do not recommend to add just new stuff to the existing functioning APIs and Processes. If no many options are defined in a protocol, the usage of it will be wild west and chaos. We need a simple and clear way on cummincation level. What is the actuall benefit?
1) in case of an incident the caller gets a error and the reason from the system - if this needs to propagated -> the caller can forward to its caller, but doesnt need to
2) the group never decided to be OCPI compliant or similar

**Comment by MKeCharIN** [comment]
pull request created
