### ISSUE TITLE
STF compliance/RCA in RCP must have "a role" and indicate their link with CTL

### ISSUE THREAD

**Issue by JMR-Gireve** [charinev/opnc#13]
STF compliance/RCA in RCP must have "a role" and indicate their link with CTL
Each RootCA certificate, stored in the RCP, is qualified 
->with the “Plug&Charge role” of the RootCA (“OEM-Root”, “MO-Root”, “V2G-Root”) and
->with the “CTL origin” (“European-CTL”, “No-CTL” …) of the certificate.  

Benefits:Necessary for being compliant with STF subgroups outputs

Impacts on players already connected via OPCP:very low negative impact. positive impact: Enrichment of RCP objects"

**Comment by MKeCharIN** [comment]
@JMR-Gireve , please create accordingly two pull requests.
