### ISSUE TITLE
STF compliance/RCP. GetRootCertificates must accept input parameters

### ISSUE THREAD

**Issue by JMR-Gireve** [charinev/opnc#14]
STF compliance/RCP. GetRootCertificates must accept input parameters

RCA in RCP must have "a role" and indicate their link with CTL: GetRootCertificates must accept input parameters:
->list of 0..n Plug&ChargeRoles
->list of 0..n CTL (including ""none"") 

Benefits:Necessary for being compliant with STF subgroups outputs and US transposition (if any)

Impacts on players already connected via OPCP: none: no change are needed (because nobody uses it)"

**Comment by MKeCharIN** [comment]
-> This parameter request (Plug&ChargeRoles) exists as "pkiType" in file "getRootCertificates" -> closed

-> In the STF only one CTL is requested or expected. Additional requests beyond STF to be discussed

**Comment by MKeCharIN** [comment]
@JMR-Gireve , please create a pull request for optional multiple CTL usage.
