### ISSUE TITLE
Openess & No Monopoly/ The origin/source of any request coming from a   P&C-EcoSystem must be explicitely identified 

### ISSUE THREAD

**Issue by JMR-Gireve** [charinev/opnc#15]
Openess & No Monopoly/ The origin/source of any request coming from a   P&C-EcoSystem must be explicitely identified :     

1°)Because a player may be connected to several "Plug&Charge   Ecosytems", It must be able to determine which ecosystem is sending an   incoming message
2°)Because a player may receive message from several players via a given   "Plug&Charge Ecosytem",It must be able to determine about which   third party is an incoming message      

Benefits:1°)Enable multi "Plug&Charge Ecosystems" and pools   services providers     2°)simplify the player systems architecture     

Impact son players already connected via OPCP:none: no change are needed

**Comment by JMR-Gireve** [comment]
We have the same thema for destination/target . Create a new issue?

**Comment by MKeCharIN** [comment]
Multi PnC-Ecosystems are enabled by the BroadcastFag and make it possible without connecting to all PnC-Ecosystems.

**Comment by MKeCharIN** [comment]
@JMR-Gireve , please create accordingly a pull request.
