### ISSUE TITLE
IT std compliance/Rest std compliance: ObjectName + Plural for Get /  POST only if data must be stored on server side 

### ISSUE THREAD

**Issue by JMR-Gireve** [charinev/opnc#18]
IT std compliance/Rest std compliance: ObjectName + Plural for Get /  POST only if data must be stored on server side 

Benefits:IT standard compliance. Implementation Cost Reduction. Maintenance cost reduction

Impact son players already connected via OPCP:none: they may ignore these codes. They can simplify and thus improve the robustness of their systems"

**Comment by MKeCharIN** [comment]
@JMR-Gireve , please create accordingly a pull request.
