### ISSUE TITLE
Complexity reduction/Need several GetSCCB

### ISSUE THREAD

**Issue by JMR-Gireve** [charinev/opnc#19]
Complexity reduction/Need several GetSCCB : 
->One related to installationProcess: a ""Get by InstallationRequest"" typically for CPO and OEM
->One related to PCID, typically for OEM: a Get By PCID""
->One related to eMAId, typically for eMSP: a Get by eMAId 

Benefits:OEM, eMSP and CPO have their custom Service and do not need to develop complex data processing.

Impact son players already connected via OPCP:none : new additional services
But opportunity to reduce complexity

**Comment by MKeCharIN** [comment]
OEM and CPO end points are already existing
("signedcontractdata/{emaid}/{pcid" and "ccp.api.v1.signedContractData.json")
