### ISSUE TITLE
Complexity reduction/How to identify a given certificate: A certificate is (uniquely) identified by (couple) {serialId +IssuerDn}. 

### ISSUE THREAD

**Issue by JMR-Gireve** [charinev/opnc#22]
Complexity reduction/How to identify a given certificate: A certificate is (uniquely) identified by (couple) {serialId +IssuerDn}. 

Do we
1°)use a kind of concatenation to build a single stringId
2°)use 2 separated datafields 

Benefits:standardisation to reduce cost and simplifu systems

Impact son players already connected via OPCP:very low"

**Comment by JMR-Gireve** [comment]
SerialId is unique, only for a given IssuerDn !

**Comment by MKeCharIN** [comment]
@JMR-Gireve , please create accordingly a pull request.

**Comment by steffenrhinow** [comment]
Please use FIngerprint sha256. Usage of one parameter instead of multiple is simplifying. Furthermore a PKI provider can define a Serial number and a common name independently. so its not unique to use serial number and IssuerDN Cross PKI wide
