### ISSUE TITLE
Key topic for Robustness/headers "OPNC-From" and "OPNC-To"

### ISSUE THREAD

**Issue by JMR-Gireve** [charinev/opnc#27]
Key topic for Robustness/headers ""OPNC-From"" and ""OPNC-To"":

The identification of fonctional actors ("Sub-CPO"", "Sub-eMSP", "Sub-OEM") is based on explicit data (http headers) and not on data processing on object's ids 

Benefits:
1°)Basic IT rule on not managing process based on data processing on object's ids
2°)Compliancy with OCPI and thus with the majority of eMSP and CPO

Impact son players already connected via OPCP:none: no change are needed"

**Comment by MKeCharIN** [comment]
Has already been discussed in the group and so far not supported to change.
Newly to be discussed in the group? Voting if needed.

**Comment by JMR-Gireve** [comment]
My suggestion is to add this mode as an option which would be described in the protocol description

Since the last discussion, we worked on the "notification flows", and saw that this kind of information (regarding the source and target identification) is mandatory for notifications

**Comment by MKeCharIN** [comment]
@JMR-Gireve , please create accordingly a pull request.
