### ISSUE TITLE
Complexity reduction/GenerateAnd Sign: Sign is optional. need of a specific input parameter 

### ISSUE THREAD

**Issue by JMR-Gireve** [charinev/opnc#28]
Complexity reduction/GenerateAnd Sign: Sign is optional:
Sign is optional. We need a dedicated and specific input parameter to activate or not the "signing"

Benefits:Basic IT rule on explicit parameters

Impact son players already connected via OPCP:none: no change are needed"

**Comment by MKeCharIN** [comment]
@JMR-Gireve , please create accordingly a pull request.
