### ISSUE TITLE
A remark/question about eMAId definition

### ISSUE THREAD

**Issue by JMR-Gireve** [charinev/opnc#4]
A remark/question about eMAId
eMAId definition is not in line with ISO15118 definition: eMAId=12(-)123(-)123456789(-)(X) → DE911ABCDEFGHI (lg=14)/ DE-911-ABCDEFGHI-X (lg=18)

**Comment by JMR-Gireve** [comment]
Why not normalizing in internal processes (database for example). But we are also talking here on input parameters. Some players might request API with the "-" separators

**Comment by steffenrhinow** [comment]
we are on the same page. this is how it's done. custom. Er can use separates but the systems should be able to map it correctly.


Steffen Rhinow

Head of Plug&Charge

Mobil: +49 172 2846215<tel:+491722846215>

***@***.******@***.***>

________________________________

**Comment by MKeCharIN** [comment]
For change to "(lg=18)", please create a corresponding pull request

**Comment by MKeCharIN** [comment]
@JMR-Gireve , please create a corresponding pull request with "(lg=18)", including comment in the code-files
