### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by cpalbr** [charinev/opnc#8]
Jerome B. wrote the following comment in the word document: 

The versioning on 1 digit is highly debatable. A semver like versioning on 3 digits would permit to introduce non breaking change while keeping the API mandatory idempotency.

How should the versioning of OPNC be designed?

**Comment by cpalbr** [comment]
Do we need 2 or 3 digits?

**Comment by steffenrhinow** [comment]
I would be for 2. less complex
major - breaking change
minor - backward compatible functions, optional parameters, descriptions


Steffen Rhinow

Head of Plug&Charge

Mobil: +49 172 2846215<tel:+491722846215>

***@***.******@***.***>

________________________________

**Comment by JMR-Gireve** [comment]
Ok for 3 levels
Major level -> Changes that impact implementation: Changes are needed in IS which implements OPNC
Minor level -> Backward compatible functional changes. No changes are required in IS which implements OPNC (except for new features)
Corrective -> No new features & No impact. Only (corrective) changes in definition, description

**Comment by MKeCharIN** [comment]
aligned in the group
